#Use an existing docker image as a base
FROM node:alpine

#Copy files
WORKDIR /app
COPY package.json .

#Download and install a dependency
RUN npm install

#Copy files
COPY . .


#Tell the image what to do when it starts
#as a container
CMD ["npm", "run", "start"]